"""Entity models persisted to State_Store / Audit_Ledger.

Implements ``Incident``, ``Responder``, ``Shelter``, ``EscalationRecord``,
``EscalationOption``, and ``AuditEntry`` per design.md §4.2.

Verification note (Req 19.8 / task 2.2 "verify first"): Pydantic v2 constraint
syntax was confirmed against the current Pydantic docs before writing these
models — numeric bounds use ``Field(ge=..., le=...)`` (inclusive bounds),
string length bounds use ``Field(max_length=..., min_length=...)``, and closed
choice sets use ``typing.Literal`` rather than a plain ``str`` + validator.
This matches ``pydantic==2.13.5`` as pinned in ``requirements.txt``.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

__all__ = [
    "Incident",
    "Responder",
    "Shelter",
    "EscalationOption",
    "EscalationRecord",
    "AuditEntry",
]


# ---------------------------------------------------------------------------
# Human-readable helpers used by EscalationRecord.template_fields()
# ---------------------------------------------------------------------------


def _to_local(iso_timestamp: str) -> str:
    """Render an ISO-8601 (with timezone) response deadline as a short local
    "HH:MM" string for the hand-authored notification templates (design.md
    §3.5). Never calls a model — purely mechanical formatting of a persisted
    field, per Req 11.3 ("no field generated by a model invocation").
    """
    # Accept "...T14:52:00+05:30" / "...T14:52:00Z" and similar ISO variants.
    from datetime import datetime

    try:
        dt = datetime.fromisoformat(iso_timestamp.replace("Z", "+00:00"))
        return dt.strftime("%H:%M")
    except ValueError:
        # Fall back to the raw string rather than raising — template
        # rendering must never fail on an unexpected but non-empty value.
        return iso_timestamp


def _humanize(action_key: str) -> str:
    """Turn a machine default-action key (e.g. ``"hold_assignment"``) into the
    short human phrase the templates in design.md §3.5 interpolate
    (e.g. "hold the assignment and keep searching for capacity").
    """
    _KNOWN: dict[str, str] = {
        "hold": "hold (nothing is sent by default)",
        "hold_assignment": "hold the assignment and keep searching for capacity",
        "send_with_standard_wording": "send with standard wording",
        "pay_now": "pay now",
        "close_request": "close the request",
    }
    if action_key in _KNOWN:
        return _KNOWN[action_key]
    # Fallback: turn "some_action_key" into "some action key".
    return action_key.replace("_", " ")


# ---------------------------------------------------------------------------
# Entities
# ---------------------------------------------------------------------------


class Incident(BaseModel):
    """One tracked hazard incident for a river reach (Req 3.3-3.10, 15.1)."""

    incident_id: str
    river_reach_id: str
    severity_band: Literal["NORMAL", "WATCH", "WARNING", "EVACUATE"]
    status: Literal["OPEN", "CLOSED"]
    affected_areas: list[str] = Field(default_factory=list)
    created_at: str  # ISO-8601 with timezone
    updated_at: str  # ISO-8601 with timezone
    last_readings: dict = Field(default_factory=dict)
    triggered_rule_ids: list[str] = Field(default_factory=list)
    rule_set_version: str


class Responder(BaseModel):
    """A registered responder available for dispatch (Req 6.1, 6.4, 13.*)."""

    responder_id: str
    name: str  # synthetic in fixtures
    home_coords: tuple[float, float]
    equipment: list[Literal["boat", "4x4", "none"]] = Field(default_factory=list)
    availability_status: Literal["AVAILABLE", "ASSIGNED"]
    active_assignment_id: str | None = None
    active_assignment_count: int = Field(default=0, ge=0)


class Shelter(BaseModel):
    """A registered shelter with a live capacity invariant (Req 6.7, 15.8)."""

    shelter_id: str
    name: str
    coords: tuple[float, float]
    total_capacity: int = Field(ge=0)
    # Invariant: 0 <= available_capacity <= total_capacity. The upper bound is
    # enforced by memory/state_store.py::decrement_shelter_capacity (task 6.1)
    # at write time; this model enforces the non-negative floor unconditionally.
    available_capacity: int = Field(ge=0)


class EscalationOption(BaseModel):
    """One selectable option offered to the coordinator on an EscalationRecord
    (Req 11.1: "between 2 and 5 available options each carrying a distinct
    option identifier").
    """

    option_id: str
    label: str


class EscalationRecord(BaseModel):
    """The persisted representation of one pending human decision (Req 11.1).

    Every field on this model is either supplied directly by the deterministic
    escalation gate (policy/escalation_policy.py) or computed mechanically
    from other persisted fields (e.g. ``template_fields()``). No field is ever
    populated by a model invocation (Req 11.3).
    """

    escalation_id: str
    incident_id: str | None = None
    escalation_type: str  # key into policy DEFAULT_ACTION / surface TEMPLATES
    status: Literal["OPEN", "RESOLVED", "RESOLVED_BY_DEFAULT"]
    decision_summary: str = Field(max_length=200)
    reason: str
    stakes: str
    options: list[EscalationOption] = Field(min_length=2, max_length=5)
    default_action: str
    response_deadline: str  # ISO-8601 with timezone
    interrupt_id: str | None = None  # set only when the pausing node used HumanInTheLoop
    run_id: str
    resolved_option_id: str | None = None
    responding_human_id: str | None = None
    resolution_timestamp: str | None = None
    resolved_by_default: bool = False
    # Added by task 16.3 (surface/escalation_service.py): tracks whether the
    # Req 11.2 out-of-band notification for *this* record has already been
    # successfully delivered, so a retried/replayed create_escalation call
    # (e.g. after a process restart) never re-notifies the coordinator for
    # the same escalation (Req 11.2's "no re-notify on resume") -- this is
    # the durable, cross-process source of truth that
    # integrations/notification_provider.py's own docstring already assumes
    # exists here, rather than relying on any single provider instance's
    # in-memory idempotency cache (which does not survive a process
    # restart/new instance). ``notification_delivery_failed`` is set when
    # every delivery attempt failed (Req 11.11), so Decision_Inbox (task
    # 25.x) can present the delivery-failure state on this record; it is
    # cleared back to ``False`` the moment a delivery later succeeds.
    notified: bool = False
    notification_delivery_failed: bool = False
    # Persisted, escalation-type-specific values needed to render the
    # hand-authored template for this escalation_type (e.g. responder_name,
    # location, occupant_count, mobility_note for "dispatch_assignment";
    # severity_band, affected_areas, audience_count for "alert_release").
    # Not model-generated — populated by the deterministic gate/tool that
    # created this record, straight from State_Store values. This is the
    # backing store for template_fields()'s "**self._type_specific_fields()"
    # expansion in design.md §4.2.
    context: dict = Field(default_factory=dict)

    def _type_specific_fields(self) -> dict:
        """Return the escalation-type-specific persisted values (design.md
        §4.2/§3.5). These come straight from ``context``, which is itself
        populated only from persisted State_Store values at record-creation
        time — never from a model call.
        """
        return dict(self.context)

    def template_fields(self) -> dict:
        """Return ONLY persisted values, for ``surface.escalation_service
        .render_template()`` (Req 11.3, design.md §3.5).

        This is deliberately a strict subset of the model's fields: it
        excludes every internal bookkeeping field (``escalation_id``,
        ``run_id``, ``interrupt_id``, ``status``, ``resolved_option_id``,
        ``responding_human_id``, ``resolution_timestamp``,
        ``resolved_by_default``) that a human-facing notification must never
        show, and it never invokes a model to compute a value — every value
        returned is either copied verbatim from a persisted field or derived
        mechanically (``_to_local``, ``_humanize``) from one.
        """
        return {
            "reason": self.reason,
            "stakes": self.stakes,
            "deadline_local": _to_local(self.response_deadline),
            "default_action_human": _humanize(self.default_action),
            **self._type_specific_fields(),
        }


class AuditEntry(BaseModel):
    """One append-only Audit_Ledger entry (Req 15.6, 16.8, 20.1-20.3)."""

    entry_id: str
    run_id: str
    timestamp: str  # ISO-8601 with timezone
    tool_call_id: str | None = None
    tool_name: str
    inputs: dict = Field(default_factory=dict)  # already redacted before construction
    outcome: str
    approving_human_id: str | None = None
    model_id: str | None = None
    input_tokens: int | None = Field(default=None, ge=0)
    output_tokens: int | None = Field(default=None, ge=0)
